version: "3.9"
services:
  tooling_frontend:
    build: .
    ports:
      - "5000:80"
    volumes:
      - tooling_frontend:/var/www/html
    links:
      - db
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: tododb
      MYSQL_HOST: mysqlserverhost
      MYSQL_USER: todo
      MYSQL_PASSWORD: password
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
    hostname: mysqlserverhost
    volumes:
      - db:/var/lib/mysql
volumes:
  tooling_frontend:
  db: